name: Go complete CI

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.23.2'
      linter-version:
        required: false
        type: string
        default: 'v1.60.1'
      ubuntu-version:
        required: false
        type: string
        default: '22.04'
      working-directory:
        required: false
        type: string
        default: '.'
      binary-name:  # Обязательный параметр для сборки
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  lint: 
    uses: ./.github/workflows/go-lint.yml
    with:
      go-version: ${{ inputs.go-version }}
      linter-version: ${{ inputs.linter-version }}
      working-directory: ${{ inputs.working-directory }}
      ubuntu-version: ${{ inputs.ubuntu-version }}

  go_test:
    uses: ./.github/workflows/go-test.yml
    needs: lint
    with:
      go-version: ${{ inputs.go-version }}
      ubuntu-version: ${{ inputs.ubuntu-version }}
      working-directory: ${{ inputs.working-directory }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  go_build:
    uses: ./.github/workflows/go-build.yml
    needs: go_test
    # Запускаем только при push в main или создании тега
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    with:
      go-version: ${{ inputs.go-version }}
      binary-name: ${{ inputs.binary-name }}