name: Go lint

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version to use (default: 1.23.2)'
        required: false
        type: string
        default: '1.23.2'
      linter-version:
        description: 'golangci-lint version to use (default: v1.60.1)'
        required: false
        type: string
        default: 'v1.60.1'
      working-directory:
        description: 'Working directory for the project (default: .)'
        required: false
        type: string
        default: '.'
      timeout:
        description: 'Linter timeout (default: 5m)'
        required: false
        type: string
        default: '5m'
      ubuntu-version:
        description: 'Ubuntu version for actions runner (default: 22.04)'
        required: false
        type: string
        default: '22.04'
      linter-config-path:
        description: 'Path to golangci-lint config (default: .golangci.yml)'
        required: false
        type: string
        default: '.golangci.yml'

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-${{ inputs.ubuntu-version }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checout code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Download dependencies
        run: go mod tidy && go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: ${{ inputs.linter-version }}
          args: --timeout=${{ inputs.timeout }} --config=${{ inputs.linter-config-path }}
          working-directory: ${{ inputs.working-directory }}
