name: Go lint

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version to use(default:1.23.2)'
        required: false
        type: string
        default: '1.23.2'
      linter-version:
        description: 'Golangci-linter version to use(default:1.60.1)'
        required: false
        type: string
        default: 'v1.60.1'
      working-directory:
        description: 'Working directory for the project(default .)'
        required: false
        type: string
        default: '.'
      timeout:
        description: 'Linter timeout(default 5m)'
        required: false
        type: string
        default: '5m'
      ubuntu-version:
        description: 'Ubuntu vers for actions run(default:22.04)'
        required: false
        type: string
        default: '22.04'

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-${{ inputs.ubuntu_version }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checout code 
        uses: actions/checkout@v4
    
      - name: Setup code
        uses: actions/setup-go@v5
        with: 
          go-version: ${{ inputs.go_version }}
          cache: true
        
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: ${{ inputs.linter-version }}
          args: --timeout=${{ inputs.timeout }}
          working-directory: ${{ inputs.working-directory }}